/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ventadesinfectantes;

import com.ventadesinfectantes.Repositories;
import users.UserInDB; // MUY IMPORTANTE
import java.util.Optional;
import javax.swing.JOptionPane; // Para los mensajes
import users.User;              // Para reconocer el modelo de usuario
import java.util.Optional;
/**
 *
 * @author GREGORY JESUS OROZCO
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contra1 = new javax.swing.JLabel();
        correologin2 = new javax.swing.JLabel();
        correologin1 = new javax.swing.JTextField();
        registraselogin = new javax.swing.JButton();
        ingresarlogin = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel2.setText("ACCEDER AL SISTEMA");

        contra1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        contra1.setText("Contraseña:");

        correologin2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        correologin2.setText("Correo:");

        registraselogin.setBackground(java.awt.SystemColor.control);
        registraselogin.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        registraselogin.setText("Registarse");
        registraselogin.addActionListener(this::registraseloginActionPerformed);

        ingresarlogin.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        ingresarlogin.setText("Ingresar");
        ingresarlogin.addActionListener(this::ingresarloginActionPerformed);

        jPasswordField1.addActionListener(this::jPasswordField1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(correologin2)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(contra1)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(correologin1)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(registraselogin)
                        .addGap(46, 46, 46)
                        .addComponent(ingresarlogin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correologin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correologin2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contra1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registraselogin)
                    .addComponent(ingresarlogin))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registraseloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraseloginActionPerformed

        Registro nuevaVentana = new Registro();
        nuevaVentana.setVisible(true);
        nuevaVentana.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_registraseloginActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void ingresarloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarloginActionPerformed
       String correoIngresado = correologin1.getText();
    String passIngresada = String.valueOf(jPasswordField1.getPassword());

    // Validar campos vacíos
    if (correoIngresado.isEmpty() || passIngresada.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos.");
        return;
    }

    // Usar la instancia de Repositories para buscar al usuario
    Repositories.getInstance().user.getByEmail(correoIngresado).ifPresentOrElse(usuario -> {
        // Si el usuario existe, validamos la contraseña
        if (usuario.password.equals(passIngresada)) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Bienvenido " + usuario.name + "!");
            
            // Abrir la ventana principal (VentaDesinfectantes)
            facturas main = new facturas();
            main.setVisible(true);
            main.setLocationRelativeTo(null);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Contraseña incorrecta.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }, () -> {
        // Si el Optional está vacío
        javax.swing.JOptionPane.showMessageDialog(this, "El correo no está registrado.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }); 
    }//GEN-LAST:event_ingresarloginActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contra1;
    private javax.swing.JTextField correologin1;
    private javax.swing.JLabel correologin2;
    private javax.swing.JButton ingresarlogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton registraselogin;
    // End of variables declaration//GEN-END:variables
}
